#!/usr/bin/env bash
# Regenera el Anexo B (logs y resultados) ejecutando todos los comandos
# y escribiendo ANEXO_B_GENERADO.md en la raíz de poc5-gdpr.
# Uso: desde poc5-gdpr, con el entorno levantado (docker compose up -d):
#   ./scripts/regenerar_anexo_b.sh

set -e
# Raíz del experimento (donde está docker-compose.yml)
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
USER_ID="${USER_ID:-a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11}"
OUT="${OUT:-$ROOT/ANEXO_B_GENERADO.md}"
DB_API_URL="${DB_API_URL:-http://localhost:8080}"

run() { "$@"; }
db_get() { curl -s "$DB_API_URL/$1" 2>/dev/null || echo "(error o servicio no disponible)"; }

echo "Generando $OUT ..."

{
  echo "# Anexo B. Logs y resultados (completo) — Generado automáticamente"
  echo ""
  echo "Fecha: $(date -Iseconds 2>/dev/null || date)"
  echo "Usuario de prueba: $USER_ID"
  echo ""
  echo "---"
  echo ""
  echo "## B.1 Resultados (evidencias)"
  echo ""
  echo "### Health (User Service)"
  echo "\`\`\`"
  curl -s http://localhost:8000/health || echo "(servicio no disponible)"
  echo ""
  echo "\`\`\`"
  echo ""
  echo "### Users (usuario de prueba)"
  echo "\`\`\`"
  db_get "users/$USER_ID"
  echo "\`\`\`"
  echo ""
  echo "### User read model (Reader)"
  echo "\`\`\`"
  db_get "evidence/read-model"
  echo "\`\`\`"
  echo ""
  echo "### Reservations"
  echo "\`\`\`"
  db_get "evidence/reservations"
  echo "\`\`\`"
  echo ""
  echo "### Analytics (analytics_user_activity)"
  echo "\`\`\`"
  db_get "evidence/analytics"
  echo "\`\`\`"
  echo ""
  echo "### Auditoría (audit_events)"
  echo "\`\`\`"
  db_get "audit/events"
  echo "\`\`\`"
  echo ""
  echo "### API TFO (GET /audit/tfo/{user_id})"
  echo "\`\`\`json"
  curl -s "http://localhost:8000/audit/tfo/$USER_ID" || echo "(servicio no disponible)"
  echo ""
  echo "\`\`\`"
  echo ""
  echo "---"
  echo ""
  echo "## B.2 Logs de los servicios"
  echo ""
  echo "### Core User Service"
  echo "\`\`\`"
  docker logs poc5_gdpr_core_user_service 2>&1 | tail -80 || echo "(contenedor no disponible)"
  echo "\`\`\`"
  echo ""
  echo "### Core Reader"
  echo "\`\`\`"
  docker logs poc5_gdpr_core_reader 2>&1 | tail -50 || echo "(contenedor no disponible)"
  echo "\`\`\`"
  echo ""
  echo "### Core Reservations"
  echo "\`\`\`"
  docker logs poc5_gdpr_core_reservations 2>&1 | tail -50 || echo "(contenedor no disponible)"
  echo "\`\`\`"
  echo ""
  echo "### Apoyo Analytics"
  echo "\`\`\`"
  docker logs poc5_gdpr_apoyo_analytics 2>&1 | tail -50 || echo "(contenedor no disponible)"
  echo "\`\`\`"
  echo ""
  echo "---"
  echo ""
  echo "*Fin del anexo generado.*"
} > "$OUT"

echo "Listo. Abre: $OUT"
