apiVersion: v1
kind: Service
metadata:
  name: currency
  labels:
    app.kubernetes.io/name: currency
spec:
  selector:
    app.kubernetes.io/name: currency
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
