apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-core
  labels:
    app.kubernetes.io/name: service-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: service-core
  template:
    metadata:
      labels:
        app.kubernetes.io/name: service-core
    spec:
      serviceAccountName: service-core-sa

      volumes:
        - name: kafka-ca
          emptyDir: {}

      containers:
        - name: service-core
          image: 345340320521.dkr.ecr.us-east-2.amazonaws.com/service-core:6495fd4426c9b87f69a3a87b073700b8acfbd903
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000

          env:
            - name: POSTGRES_DB
              value: "postgres"

          envFrom:
            - secretRef:
                name: travelhub-postgres

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"