apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: service-core
  labels:
    app.kubernetes.io/name: service-core
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: service-core
  template:
    metadata:
      labels:
        app.kubernetes.io/name: service-core
    spec:
      serviceAccountName: service-core-sa
      volumes:
        - name: kafka-ca
          emptyDir: {}
      containers:
        - name: service-core
          image: 345340320521.dkr.ecr.us-east-2.amazonaws.com/service-core:5af036149597196443238c0e2a712dd3769def7d
          imagePullPolicy: IfNotPresent

          command: [ "uvicorn" ]
          args:
            - "main:app"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "8000"

          ports:
            - name: http
              containerPort: 8000

          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: KAFKA_LOCAL
              value: "false"
            - name: MAILER
              value: "http://service-soport:80/notification/send-email"

          envFrom:
            - secretRef:
                name: travelhub-postgres

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3

  strategy:
    canary:
      steps:
        - setWeight: 50       # 50% del tráfico a la nueva versión
        - pause: {duration: 60s}
        - setWeight: 100      # 100% del tráfico si todo OK