apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-core-sa
  namespace: apps
  labels:
    app.kubernetes.io/name: service-core
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::345340320521:role/eks-service-soport-s3-read-role
