apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-soport
  labels:
    app.kubernetes.io/name: service-soport
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: service-soport
  template:
    metadata:
      labels:
        app.kubernetes.io/name: service-soport
    spec:
      serviceAccountName: service-soport-sa

      containers:
        - name: service-soport
          image: 345340320521.dkr.ecr.us-east-2.amazonaws.com/service-soport:e1f8d79c9e611712c38960444531e7c7e0b72df4
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000

          envFrom:
            - secretRef:
                name: travelhub-env

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"