apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-soport
  labels:
    app.kubernetes.io/name: service-soport
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: service-soport
  template:
    metadata:
      labels:
        app.kubernetes.io/name: service-soport
    spec:
      serviceAccountName: service-soport-sa

      volumes:
        - name: kafka-ca
          emptyDir: {}


      containers:
        - name: service-soport
          image: 345340320521.dkr.ecr.us-east-2.amazonaws.com/service-soport:bea2bfadcf06f2acf5e3aa3bd7598e16d4c5442e
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000

          envFrom:
            - secretRef:
                name: travelhub-postgres

          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"