apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: travelhub-postgres
  namespace: service-soport
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: travelhub-postgres
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: bd_travelhub
        property: host
    - secretKey: POSTGRES_PORT
      remoteRef:
        key: bd_travelhub
        property: port
    - secretKey: POSTGRES_USER
      remoteRef:
        key: bd_travelhub
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: bd_travelhub
        property: password
    - secretKey: TOKEN_SOPORT_SERVICES
      remoteRef:
        key: soport_token
        property: soport_token
    - secretKey: RESEND_API_KEY
      remoteRef:
        key: send_email
        property: send_email
