apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: travelhub-postgres
  namespace: service-soport
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: travelhub-postgres
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: bd_travelhub
        property: host
    - secretKey: POSTGRES_PORT
      remoteRef:
        key: bd_travelhub
        property: port
    - secretKey: POSTGRES_USER
      remoteRef:
        key: bd_travelhub
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: bd_travelhub
        property: password