apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - platform/namespace.yaml
  - platform/external-secrets
  - platform/rol_rbac.yaml
  - platform/argo-rollouts-configmap.yaml
  - platform/argo-rollouts-leases-rbac.yaml
  - service-soport
  - service-core
  - service-external
  - worker
