apiVersion: v1
kind: Service
metadata:
  name: notification
  labels:
    app.kubernetes.io/name: notification
spec:
  selector:
    app.kubernetes.io/name: notification
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
