name: Run Pytest per Service

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
    inputs:
      service:
        description: "Nombre de un servicio específico (opcional)"
        required: false
        default: ""

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run tests per service
        run: |
          echo "Preparing services list..."

          if [ -n "${{ github.event.inputs.service }}" ]; then
            SERVICES="${{ github.event.inputs.service }}"
          else
            SERVICES=$(cat test.txt)
          fi

          for service in $SERVICES
          do
            echo "=============================="
            echo "Testing service: $service"
            echo "=============================="

            SERVICE_PATH="services/$service"

            if [ -d "$SERVICE_PATH" ]; then
              cd $SERVICE_PATH

              echo "Creating virtual environment..."
              python -m venv venv
              source venv/bin/activate

              echo "Installing dependencies..."
              python -m pip install --upgrade pip

              if [ -f "requirements.txt" ]; then
                pip install -r requirements.txt
              fi
              if [ -f "requirements-dev.txt" ]; then
                pip install -r requirements-dev.txt
              fi
              pip install pytest

              echo "Running tests..."
              pytest || exit 1

              deactivate
              cd - > /dev/null
            else
              echo "❌ Service $service not found!"
              exit 1
            fi

          done